### ISSUE TITLE
MetFrag Web tool retrieving candidates error

### ISSUE THREAD

**Issue by Havefar** [ipb-halle/MetFrag#14]
Hi,

It seems like the wonderful MetFrag Web tool is not working currently? I get "Database error - Failed to retrieve candidates" and "error fetching candidates" when trying to retrieve candidates.

Thanks for a great tool!

Best,
Jesper

**Comment by schymane** [comment]
It seems to be working again now, can you confirm?

**Comment by Havefar** [comment]
It works a bit on and off. But it works most of the times :-) thank you

Best,
Jesper Havelund

Den 24. feb. 2020 kl. 09.40 skrev Emma Schymanski <notifications@github.com>:

﻿

It seems to be working again now, can you confirm?

**Comment by janajohansson** [comment]
Hi! I have the same issue. Beta cannot retrieve candidates while the 2010 version can retrieve candidates but not process them.

**Comment by schymane** [comment]
https://msbi.ipb-halle.de/MetFrag/ seems to be working fine this morning; but https://msbi.ipb-halle.de/MetFragBeta/ is not looking too good... @sneumann

**Comment by sneumann** [comment]
Yes, hickup in our cluster. Every now and then internal IPs get messed up :-( Fixed now. Yours, Steffen
