### ISSUE TITLE
MetfragCL error when retrieving more than 1K candidates

### ISSUE THREAD

**Issue by DennysLB** [ipb-halle/MetFrag#18]
Hi,
I am running MetfragCL using PubChem data base and getting this error once candidates have been stored: Exception in thread "main" java.lang.OutOfMemoryError:Java heap space. Notice that  I'm retrieving 1847 candidates!
I run the web version and it worked. However, the number of candidates is lower than in the CL version and structures are not included in the xls output file.

Appreciate any help!

Thanks

**Comment by schymane** [comment]
This is something you'll have to tweak your side, as MetFragCL can certainly handle that number of candidates, see eg: https://stackoverflow.com/questions/2381849/exception-in-thread-main-java-lang-outofmemoryerror-java-heap-space

**Comment by DennysLB** [comment]
> This is something you'll have to tweak your side, as MetFragCL can certainly handle that number of candidates, see eg: https://stackoverflow.com/questions/2381849/exception-in-thread-main-java-lang-outofmemoryerror-java-heap-space

Hi,
I found a solution in the post you referenced.

Thanks a lot!
