### ISSUE TITLE
Database options

### ISSUE THREAD

**Issue by mnewmeyer** [ipb-halle/MetFrag#20]
Hi MetFrag team!

First, I just wanted to say how great this resource is and thank you all for your work and dedication to putting it together and constantly improving it.

I have been working with MetFragWeb and when I recently accessed the page I saw that the database options have been limited to only the Server Databases and Uploaded Databases. I was wondering if access to the custom databases would be restored for the Web-based application?

Thanks so much!

**Comment by schymane** [comment]
I see all options still, are you using a different website?
https://msbi.ipb-halle.de/MetFrag/

![image](https://user-images.githubusercontent.com/4070141/122066268-e6081080-cdf2-11eb-8b01-a8fa58211190.png)

**Comment by schymane** [comment]
...otherwise we do have links to most of these on Zenodo but some are too big to upload practically via the website ... (hence we offer them pre-loaded)

**Comment by mnewmeyer** [comment]
Ah, thank you for clarifying the url. I previously was using https://msbi.ipb-halle.de/MetFragBeta/

In fact, starting at https://ipb-halle.github.io/MetFrag/ and clicking on "Learn More" under MetFragWeb and then "MetFrag Web tool" leads to https://msbi.ipb-halle.de/MetFragBeta/

I will bookmark the other address. Thank you!

**Comment by schymane** [comment]
Theoretically they should be mirrors (because when we add new databases, they first appear on the Beta site to test), but something may be up with MetFragBeta. 
@sneumann will have to look into updating the *.io link (MetFrag has more resources than MetFragBeta) and he'll also have to see what's up with Beta ... not under my direct control ;-)

**Comment by mnewmeyer** [comment]
Thanks so much again! Unless you think it would be useful to keep this open, I can close the issue.

**Comment by schymane** [comment]
Please keep open until @sneumann resolves the open issues (updating link and checking the health of MetFragBeta). Unless @sneumann has another opinion ... but otherwise I will have to open two new issues...

**Comment by sneumann** [comment]
I have an inkling what is happening, will check tomorrow. Yours Steffen


I blame Android for the brevity and typos

**Comment by sneumann** [comment]
Hi, https://ipb-halle.github.io/MetFrag/projects/metfragweb/ is now pointing to the main /MetFrag and not to the /MetFragBeta anymore; and I fixed some issues that re-occurred with the file databases. 
In case problems persist, please re-open the issue. Yours, Steffen
