### ISSUE TITLE
MetFrag Web tool unavailable

### ISSUE THREAD

**Issue by patrickmon38** [ipb-halle/MetFrag#21]
Hi there, it seems the web version of MetFrag is down. I've tried a couple of browsers, but the web tool is not loading.

**Comment by schymane** [comment]
Always Friday afternoon / evenings ... I can confirm I just tried and neither MetFrag nor Beta load for me either. @sneumann is it possible to give the server some TLC?

**Comment by schymane** [comment]
There is server maintenance at Halle until tomorrow  - sorry for the inconvenience. They were unable to post a message to communicate this ...
Hopefully up again soon!

**Comment by sneumann** [comment]
Update: the institute storage infrastructure work is taking longer than expected, 
and we won't be back online today. Sorry for the inconvenience, Yours, Steffen

**Comment by sneumann** [comment]
Hi, servers have been restarted. 
Note that there will be another maintenance, possibly on 04.12.2021. 
Yours, Steffen

**Comment by sneumann** [comment]
I also (finally!) might have found a way to place a downtime notice on all our services. Will try that for 04.12.2021 downtime. Yours, Steffen
