### ISSUE TITLE
Can I output the structure of the fragments?

### ISSUE THREAD

**Issue by josiehong** [ipb-halle/MetFrag#25]
Hi, everyone, 

I tried `MetFrag_CL` and got the output fragment formula with the corresponding peaks. However, I noticed that in `MetFragWeb`, the structures of the fragments can be highlighted. Therefore, I am curious whether it is possible to output the SMILES or other representations of the fragment structures through `MetFrag_CL` or `MetFragR`.

Thanks,
Josie

**Comment by schymane** [comment]
Hi @JosieHong you can chose some of the more "extended" output options in MetFragCL to export more details about the fragment structures, you can try out the different options and see which one works best for your use case: 

`# SDF, XLS, CSV, ExtendedXLS, ExtendedFragmentsXLS`

See https://ipb-halle.github.io/MetFrag/projects/metfragcl/

**Comment by josiehong** [comment]
Thanks for the response! 

When I use `ExtendedFragmentsXLS`, the output looks like this: 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/J0siee/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/J0siee/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
</head>

<body link="#467886" vlink="#96607D">


Score | MonoisotopicMass | SMILES | InChIKey | AutomatedLossFingerprintAnnotationScore_Matches | AutomatedPeakFingerprintAnnotationScore | NoExplPeaks | NumberPeaksUsed | InChI | AutomatedLossFingerprintAnnotationScore_Probtypes | MaximumTreeDepth | Identifier | AutomatedPeakFingerprintAnnotationScore_Values | ExplPeaks | AutomatedPeakFingerprintAnnotationScore_Probtypes | InChIKey2 | InChIKey1 | AutomatedLossFingerprintAnnotationScore | IUPACName | FragmenterScore | AutomatedPeakFingerprintAnnotationScore_Matches | MolecularFormula | FragmenterScore_Values | FormulasOfExplPeaks | AutomatedLossFingerprintAnnotationScore_Values | XlogP3
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2.9717380725012146 | 348.926284 | CCOP(=O)(OC1=NC(=C(C=C1Cl)Cl)Cl)SCC | BVDLSHNBSLRLNB-UHFFFAOYSA-N | 0 | -65.02739738455975 | 8 | 25 | InChI=1S/C9H11Cl3NO3PS/c1-3-15-17(14,18-4-2)16-9-7(11)5-6(10)8(12)13-9/h5H,3-4H2,1-2H3 | 3:2.7419776793694172E-8:18.01054;3:3.6536317629500324E-8:28.03136;3:3.33000333000333E-5:196.92012;3:3.6536317629500324E-8:28.03132;3:3.33044694598015E-5:178.90958;3:2.7419776793694172E-8:18.0105;3:3.33000333000333E-5:196.92008;3:3.33044694598015E-5:178.90958;3:1.4280206206177619E-5:77.93296;3:1.4279798369247027E-5:105.96426;3:4.7612925957138844E-6:123.97476;3:5.881315062047874E-6:152.00608;3:3.6536317629500324E-8:28.0313;3:4.524825454858079E-7:46.0418;3:4.524825454858079E-7:46.04182;3:3.6536317629500324E-8:28.03132;4:6.854944198423542E-7:18.0105;4:6.854944198423542E-7:18.01051;4:6.854944198423542E-7:18.01057;4:6.854944198423542E-7:18.01057;4:1.2351760958445264E-6:27.01058;4:1.8518148155555408E-5:28.00559;4:9.134079407375081E-7:28.03123;4:9.134079407375081E-7:28.03124;4:9.134079407375081E-7:28.03127;4:9.134079407375081E-7:28.03129;4:9.134079407375081E-7:28.0313;4:9.134079407375081E-7:28.03132;4:4.187582244115274E-6:43.0051;4:1.1312063637145196E-5:46.04181;4:1.1312063637145196E-5:46.04186;4:3.6337045574358607E-6:56.06255;4:3.6337045574358607E-6:56.06256;4:3.6337045574358607E-6:56.06263;4:1.3886805868008688E-4:61.95584;4:1.3886805868008688E-4:61.95586;4:0.0012483771097573154:72.96204;4:4.2370439669578356E-5:74.07312;4:4.2370439669578356E-5:74.07313;4:3.5700515515444043E-4:77.93296;4:4.629398159721643E-5:79.96634;4:4.629398159721643E-5:79.96639;4:4.629398159721643E-5:79.96643;4:8.33258340082726E-5:79.99207;4:4.997401351297325E-4:80.93265;4:5.9518991319750315E-5:82.98274;4:3.569847638902771E-4:89.98716;4:0.0024935168561739476:95.92644;4:0.0024935168561739476:95.92685;4:4.997401351297325E-4:95.94346;4:4.997401351297325E-4:95.94353;4:4.997401351297325E-4:95.94384;4:0.0024935168561739476:96.93048;4:3.1239456683369355E-4:100.97663;4:3.1239456683369355E-4:100.97666;4:2.4992002559181056E-4:100.99331;4:0.0024935168561739476:104.96094;4:2.7769446943694666E-4:106.99437;4:4.1647925100371497E-4:107.98064;4:4.1647925100371497E-4:107.98101;4:6.24562806035775E-4:107.99766;4:6.24562806035775E-4:107.99766;4:6.24562806035775E-4:107.99769;4:0.0024935168561739476:122.95442;4:0.0024935168561739476:122.97144;4:2.776883004365259E-4:122.98809;4:0.0024935168561739476:122.99717;4:0.0024935168561739476:123.94106;4:0.0024935168561739476:123.95774;4:0.0024935168561739476:123.95808;4:1.1903231489284709E-4:123.97473;4:1.1903231489284709E-4:123.97478;4:1.1903231489284709E-4:123.97513;4:2.082829982754167E-4:123.98381;4:3.123828564288391E-4:123.99141;4:6.245784095735378E-4:124.97845;4:0.0024935168561739476:129.00793;4:8.326117364950375E-4:132.9985;4:0.0024932681759250023:136.02898;4:6.24562806035775E-4:144.98505;4:2.272128257095856E-4:151.00276;4:8.325840077263796E-4:151.9894;4:8.325562808045824E-4:161.00409;4:8.325840077263796E-4:168.91449;4:8.326117364950375E-4:178.90959;4:8.326117364950375E-4:178.90959;4:8.326117364950375E-4:178.90962;4:8.325008325008324E-4:196.92016;4:8.325840077263796E-4:196.94585;4:0.0024935168561739476:206.95747;4:0.0024935168561739476:206.96655;4:0.0024935168561739476:207.94451;4:0.0012483771097573154:216.96163;4:8.325840077263796E-4:224.97712;4:0.0024935168561739476:252.98271 | 2 | 88406203 | NA | 124.98212_19.9;142.99266_36.7;153.01348_105.4;171.02398_406.8;197.92748_999.0;275.86044_10.9;303.89174_17.1;321.90224_699.4 | 3:1.8515432613083006E-5:124.98212;3:3.844970778222086E-5:142.99266;3:6.245706077072014E-5:153.01348;3:1.6641704110500916E-4:171.02398;3:1.248439450686642E-4:197.92748;3:2.493143854400399E-4:275.86044;3:2.4925224327018947E-4:303.89174 | UHFFFAOYSA | BVDLSHNBSLRLNB | -916.5947602754352 | 2,3,5-trichloro-6-[ethoxy(ethylsulfanyl)phosphoryl]oxypyridine | 345.6667936748575 | 0 | C9H11Cl3NO3PS | 335.0;607.0;832.0;372.0;335.0;460.0;435.0;607.0 | 124.98212:[C2H5O2PS]+H+;142.99266:[C2H5O3PS+2H]+H+;153.01348:[C4H10O2PS]+;171.02398:[C4H10O3PS+H]+H+;197.92748:[C5HCl3NO+H]+H+;275.86044:[C5HCl3NO2PS]+H+;303.89174:[C7H6Cl3NO2PS]+;321.90224:[C7H6Cl3NO3PS+H]+H+ | NA | 3.9



</body>

</html>

I thought the column `FormulasOfExplPeaks` ccontained the fragment formulas rather than the fragment structures. Also, I tried converting tools from [here](https://ipb-halle.github.io/MetFrag/projects/converter/), but the converted `xlsx` file is the same as before. Did I miss anything?

**Comment by schymane** [comment]
Hi @JosieHong - one of the extended output XLSX files should contain the images that you also see on the web, and one of them only contains the formulas, like you said. If neither of the files contain images then perhaps this is a bug, but I only see output from one in your issue. The conversion tools will not help you in this case, they are for other purposes. 
We tried to output fragment structures (as SMILES/SMARTS) in the past but it was challenging because the aromaticity state changes due to the fragmentation and it's almost impossible to align the Hs with the fragment formula (often, rings that were aromatic then became alkyl chain systems, for instance, which is not an accurate representation of reality). It worked better to create images because @c-ruttkies could anchor the location of the fragment in the structure more easily than the number of Hs written explicitly at different locations. It's basically a problem of implicit vs explicit H handling in SMILES/SMARTS that is not easy to solve in an automatic fashion with the underlying toolkit in use ... especially since it's not always clear where all the Hs are in the fragmentation process ...

**Comment by josiehong** [comment]
Thanks a lot, Emma! I got your point.👍
